### ISSUE TITLE
como inserir quebra de página?

### ISSUE THREAD

**Issue by gferreira** [educkf/paginar#3]
é possível inserir quebras de página em um html (por exemplo entre uma folha de rosto e o restante do texto)?

**Comment by educkf** [comment]
Oi @gferreira!

Para inserir uma quebra de página, precisa apenas de uma classe de CSS que quebre a coluna. A maneira como colunamos o texto é por meio propriedade de `columns` (link para [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/columns). Assim, as demais propriedades de estilo que a modificam devem funcionar. Por exemplo:

```html
<style>
.page-break {
    break-before: column;
}
  
p {
  text-indent: 4rem;
}
</style>

<paginate-content id="pagination-el" book-title="Título do livro">
    <div slot="content">
        <p>Conteúdo de uma pagina.</p>
        <div class="page-break"></div> <!-- AQUI -->
        <p>Conteúdo da próxima página.</div>
    </div>
</paginate-content>
```

A classe `.page-break` servirá como quebra de coluna (e assim, quebra de "pagina"  também). Atenção apenas que o `<style>` deve ser fora do componente de `<paginate-content>`.

**Comment by gferreira** [comment]
perfeito. obrigado!
