### ISSUE TITLE
licença de uso

### ISSUE THREAD

**Issue by gferreira** [educkf/paginar#4]
salve Eduardo, muito obrigado por tornar o sistema de paginação público.

sob qual [licença de uso](http://choosealicense.com/) o software está sendo disponibilizado?

**Comment by educkf** [comment]
Oi @gferreira!

Não tinhamos mesmo licença de uso ainda definida. Me parece que a mais simples para nossa situação é MIT mesmo. Incluí o arquivo no repositorio:

https://github.com/sabia-publisher/paginar/blob/main/LICENSE.md

**Comment by gferreira** [comment]
beleza. obrigado!
