### ISSUE TITLE
URL do botão Homepage

### ISSUE THREAD

**Issue by gferreira** [educkf/paginar#5]
é possível definir uma URL diferente para o link do botão Homepage? 

por exemplo, para retornar para o index de livros e não para o início do site.

obrigado

**Comment by educkf** [comment]
Oi @gferreira!

Para mudar o link da URL da home, devemos adicionar uma configuração ao web component, conforme exemplo abaixo. Caso esse item `homeUrl` nao exista, o botão de home irá desaparecer.

```html
<paginate-content id="pagination-el">
    <div slot="content">
        <p>Conteúdo de uma pagina.</p>
    </div>
</paginate-content>

<script>
    const settings = {
        homeUrl: 'https://sabia.pub'
    }

    const paginationEl = document.getElementById('pagination-el')
    if (paginationEl) {
        paginationEl.setAttribute("reader-settings", JSON.stringify(settings))
    }
</script>
```

Para a lista completa de parâmetros, pode dar uma [olhada aqui](https://github.com/sabia-publisher/paginar/tree/main#parametros-de-customiza%C3%A7%C3%A3o-dispon%C3%ADveis).

**Comment by gferreira** [comment]
maravilha. obrigado!
